'use client'

/**
 * Product Entry Widget for Chat
 * Mini-form for adding products within the chat interface
 */

import { useState, useRef } from 'react'
import { Package, Upload, Check, Loader2, X } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { toast } from 'sonner'
import { apiClient } from '@/lib/api-client'
import { useAutoGenerateDescription } from '@/hooks/useAutoGenerateDescription'

interface ProductData {
  name: string
  description: string
  hsn_code?: string
  image_url?: string
  specifications?: {
    grade?: string
    origin?: string
    color?: string
    purity?: string
    moisture_content?: string
    shelf_life?: string
    moq?: string
    lead_time?: string
  }
  key_benefits?: string[]
}

interface ProductEntryWidgetProps {
  field: string
  config?: {
    label?: string
    required_fields?: string[]
    show_specifications?: boolean
    show_benefits?: boolean
  }
  onComplete: (product: ProductData) => void
  disabled?: boolean
}

export function ProductEntryWidget({
  field,
  config = {},
  onComplete,
  disabled = false,
}: ProductEntryWidgetProps) {
  const { generateProductFields, isGenerating } = useAutoGenerateDescription()

  const [formData, setFormData] = useState<ProductData>({
    name: '',
    description: '',
    hsn_code: '',
    image_url: '',
    specifications: {
      grade: '',
      origin: '',
      color: '',
      purity: '',
      moisture_content: '',
      shelf_life: '',
      moq: '',
      lead_time: '',
    },
    key_benefits: [''],
  })

  const [uploading, setUploading] = useState(false)
  const [preview, setPreview] = useState<string | null>(null)
  const [isSubmitting, setIsSubmitting] = useState(false)
  const fileInputRef = useRef<HTMLInputElement>(null)

  const label = config.label || 'Add Product'
  const showSpecifications = config.show_specifications !== false
  const showBenefits = config.show_benefits !== false

  const handleChange = (field: keyof ProductData, value: any) => {
    setFormData(prev => ({
      ...prev,
      [field]: value,
    }))
  }


  const handleImageSelect = async (e: React.ChangeEvent<HTMLInputElement>) => {
    console.log('🖼️ Product image select triggered')
    const file = e.target.files?.[0]
    if (!file) {
      console.log('❌ No file selected')
      return
    }

    console.log('📁 File selected:', file.name, file.type, file.size)

    if (!file.type.startsWith('image/')) {
      toast.error('Please select an image file')
      return
    }

    if (file.size > 5 * 1024 * 1024) {
      toast.error('File size must be less than 5MB')
      return
    }

    try {
      setUploading(true)
      console.log('⬆️ Starting upload...')

      // Show preview
      const reader = new FileReader()
      reader.onload = (e) => {
        const preview = e.target?.result as string
        console.log('👁️ Preview generated:', preview?.substring(0, 50) + '...')
        setPreview(preview)
      }
      reader.readAsDataURL(file)

      // Upload via backend
      console.log('☁️ Uploading image...')
      const url = await apiClient.uploadImage(file, 'products')
      console.log('✅ Upload complete. URL:', url)

      handleChange('image_url', url)
      console.log('💾 Updated formData.image_url')
      toast.success('Image uploaded successfully!')
    } catch (error: any) {
      console.error('❌ Upload error:', error)
      toast.error(error?.message || 'Failed to upload image')
      setPreview(null)
    } finally {
      setUploading(false)
    }
  }

  const handleRemoveImage = () => {
    handleChange('image_url', '')
    setPreview(null)
    if (fileInputRef.current) {
      fileInputRef.current.value = ''
    }
  }


  const handleSubmit = async () => {
    console.log('📝 Product submit - Current formData:', formData)

    // Validate required fields
    if (!formData.name.trim()) {
      toast.error('Product name is required')
      return
    }

    try {
      setIsSubmitting(true)

      // Generate product fields (description, specifications, benefits) in background
      const result = await generateProductFields(formData.name, {
        product_name: formData.name,
      })

      if (result) {
        // Merge generated fields with form data
        const completeData = {
          ...formData,
          description: result.description || formData.description,
          specifications: {
            ...formData.specifications,
            ...result.specifications,
            origin: 'India' // Always set origin to India
          },
          key_benefits: result.key_benefits && result.key_benefits.length > 0 ? result.key_benefits : formData.key_benefits
        }

        // Filter out empty benefits
        const cleanedData = {
          ...completeData,
          key_benefits: (completeData.key_benefits || []).filter(b => b.trim() !== ''),
        }

        console.log('✅ Product submit - Sending data:', cleanedData)
        onComplete(cleanedData)
      } else {
        throw new Error('Failed to generate product fields')
      }
    } catch (error: any) {
      console.error('Submit error:', error)
      toast.error('Failed to add product', {
        description: error?.message || 'Please try again'
      })
    } finally {
      setIsSubmitting(false)
    }
  }

  const isValid = formData.name.trim() !== ''

  return (
    <div className="mt-3 p-4 bg-white rounded-lg border-2 border-gray-200 space-y-4">
      {/* Header */}
      <div className="flex items-center gap-2 text-sm text-gray-700 font-medium pb-2 border-b border-gray-200">
        <Package className="w-4 h-4 text-teal-600" />
        {label}
      </div>

      {/* Basic Fields */}
      <div className="space-y-3">
        <div>
          <Label htmlFor="product-name" className="text-sm font-medium text-gray-700">
            Product Name <span className="text-red-500">*</span>
          </Label>
          <Input
            id="product-name"
            type="text"
            value={formData.name}
            onChange={(e) => handleChange('name', e.target.value)}
            placeholder="e.g., Basmati Rice"
            disabled={disabled}
            className="mt-1"
          />
        </div>

        <div>
          <Label htmlFor="product-hsn" className="text-sm font-medium text-gray-700">
            HSN Code
          </Label>
          <Input
            id="product-hsn"
            type="text"
            value={formData.hsn_code}
            onChange={(e) => handleChange('hsn_code', e.target.value)}
            placeholder="e.g., 1006"
            disabled={disabled}
            className="mt-1"
          />
        </div>
      </div>

      {/* Image Upload */}
      <div>
        <Label className="text-sm font-medium text-gray-700 mb-2 block">
          Product Image
        </Label>

        <input
          ref={fileInputRef}
          type="file"
          accept="image/*"
          onChange={handleImageSelect}
          disabled={disabled || uploading}
          className="hidden"
        />

        {!formData.image_url && !preview ? (
          <Button
            type="button"
            onClick={() => fileInputRef.current?.click()}
            disabled={disabled || uploading}
            variant="outline"
            className="w-full h-9 border-2 border-dashed border-gray-300 hover:border-teal-500 hover:bg-teal-50 text-sm"
          >
            {uploading ? (
              <>
                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                Uploading...
              </>
            ) : (
              <>
                <Upload className="w-4 h-4 mr-2" />
                Choose Image
              </>
            )}
          </Button>
        ) : (
          <div className="relative rounded-lg overflow-hidden border-2 border-gray-200">
            <img
              src={preview || formData.image_url || ''}
              alt="Product preview"
              className="w-full h-32 object-cover"
            />
            {formData.image_url && !disabled && (
              <button
                type="button"
                onClick={handleRemoveImage}
                className="absolute top-2 right-2 bg-red-500 text-white rounded-full p-1.5 shadow-lg hover:bg-red-600 transition-colors"
              >
                <X className="w-3 h-3" />
              </button>
            )}
          </div>
        )}
      </div>

      {/* Submit Button */}
      <Button
        onClick={handleSubmit}
        disabled={disabled || !isValid || isSubmitting}
        className="w-full h-10 bg-gradient-to-r from-teal-600 to-emerald-600 hover:from-teal-700 hover:to-emerald-700 text-white font-medium text-sm shadow-md"
      >
        {isSubmitting ? (
          <>
            <Loader2 className="w-4 h-4 mr-2 animate-spin" />
            Adding Product...
          </>
        ) : (
          <>
            <Check className="w-4 h-4 mr-2" />
            Add Product
          </>
        )}
      </Button>
    </div>
  )
}