'use client'

import { useState } from 'react'

export interface ProductGenerationResult {
  description: string
  specifications: {
    grade?: string
    origin?: string
    color?: string
    purity?: string
    moisture_content?: string
    shelf_life?: string
    moq?: string
    lead_time?: string
  }
  key_benefits: string[]
}

export function useAutoGenerateDescription() {
  const [isGenerating, setIsGenerating] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const generateCategoryDescription = async (
    categoryName: string,
    context: Record<string, any>
  ): Promise<string> => {
    if (!categoryName.trim()) {
      setError('Category name is required')
      return ''
    }

    setIsGenerating(true)
    setError(null)

    try {
      const baseUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000'
      const token = typeof window !== 'undefined' ? localStorage.getItem('access_token') : null

      const response = await fetch(`${baseUrl}/api/ai-assistant/generate`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          operation: 'auto-generate',
          field_type: 'category',
          current_text: '',
          context: {
            ...context,
            category_name: categoryName
          }
        })
      })

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({ detail: 'Generation failed' }))
        throw new Error(errorData.detail || 'Generation failed')
      }

      const result = await response.json()
      setIsGenerating(false)
      return result.description || ''
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Failed to generate description'
      setError(message)
      setIsGenerating(false)
      return ''
    }
  }

  const generateProductFields = async (
    productName: string,
    context: Record<string, any>
  ): Promise<ProductGenerationResult | null> => {
    if (!productName.trim()) {
      setError('Product name is required')
      return null
    }

    setIsGenerating(true)
    setError(null)

    try {
      const baseUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000'
      const token = typeof window !== 'undefined' ? localStorage.getItem('access_token') : null

      const response = await fetch(`${baseUrl}/api/ai-assistant/generate`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          operation: 'auto-generate',
          field_type: 'product',
          current_text: '',
          context: {
            ...context,
            product_name: productName
          }
        })
      })

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({ detail: 'Generation failed' }))
        throw new Error(errorData.detail || 'Generation failed')
      }

      const result = await response.json() as ProductGenerationResult

      setIsGenerating(false)
      return result
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Failed to generate product fields'
      setError(message)
      setIsGenerating(false)
      return null
    }
  }

  return {
    generateCategoryDescription,
    generateProductFields,
    isGenerating,
    error
  }
}